---
# Interactive inputs for HANA HA

- name: Interactive input - Gather inputs for type hana
  ansible.builtin.include_tasks:
    file: "../../tasks/interactive_hana.yml"

# Mandatory inputs
- name: Interactive input - sap_vm_provision_ha_vip_hana_primary
  ansible.builtin.pause:
    prompt: |
      Please enter Virtual IP for HANA Primary server. Platform specific recommendations:
      AWS:                  the VIP must be **outside** of any VPC Subnet ranges (e.g. 192.168.100.102/32)
      GCP:                  the VIP must be within the VPC Subnetwork range attached to GCP Backend Service for the Internal passthrough Network Load Balancer (e.g. 10.10.10.10/32)
      IBM Cloud:            the VIP is within the VPC Subnet range and is statically defined by the IBM Cloud Load Balancer [NLB L4 or ALB L7], variable should be commented out
      IBM Cloud, Power VS:  the VIP must be within the IBM Power Infrastructure VLAN Subnet range (e.g. 192.168.4.4/26)
      MS Azure:             the VIP must be within the VNet Subnet range attached to the Azure Load Balancer [NLB L4] (e.g. 10.10.10.10/22)
      IBM PowerVM:          the VIP must be within the VLAN Subnet range
      OVirt KVM:            the VIP must be within the VLAN Subnet range
      KubeVirt:             the VIP must be within the VLAN Subnet range
  register: sap_vm_provision_ha_vip_hana_primary_register
  no_log: true
  when: sap_vm_provision_ha_vip_hana_primary is not defined or not sap_vm_provision_ha_vip_hana_primary


- name: Interactive input - Set facts from prompts - sap_hana_ha
  ansible.builtin.set_fact:
    sap_vm_provision_ha_vip_hana_primary: "{{ sap_vm_provision_ha_vip_hana_primary_register.user_input
      if sap_vm_provision_ha_vip_hana_primary_register.user_input is defined and sap_vm_provision_ha_vip_hana_primary_register.user_input
      else sap_vm_provision_ha_vip_hana_primary }}"
