---
# Interactive inputs for HANA

# Mandatory inputs
- name: Interactive input - sap_hana_product_input
  ansible.builtin.pause:
    prompt: |
      Please select HANA product from list: {{ sap_hana_install_media_dictionary.keys() }}
      Products are defined in sap_hana_install_media_dictionary
  register: sap_hana_product_input_register
  failed_when: sap_hana_product_input_register.user_input not in sap_hana_install_media_dictionary.keys()
  when: sap_hana_product_input is not defined or not sap_hana_product_input

- name: Interactive input - sap_hana_install_use_master_password
  ansible.builtin.pause:
    prompt: "Please select if SAP HANA master password should be used for all passwords (y/n). Default: y"
  register: sap_hana_install_use_master_password_register
  no_log: true
  when: sap_hana_install_use_master_password is not defined

- name: Interactive input - sap_hana_install_master_password
  ansible.builtin.pause:
    prompt: "Please enter master password of SAP HANA."
  register: sap_hana_install_master_password_register
  no_log: true
  when: sap_hana_install_master_password is not defined or not sap_hana_install_master_password

- name: Interactive input - sap_system_hana_db_sid
  ansible.builtin.pause:
    prompt: "Please enter System ID (SID) of SAP HANA."
  register: sap_system_hana_db_sid_register
  no_log: true
  when: sap_system_hana_db_sid is not defined

- name: Interactive input - sap_system_hana_db_instance_nr
  ansible.builtin.pause:
    prompt: "Please enter Instance number of SAP HANA."
  register: sap_system_hana_db_instance_nr_register
  no_log: true
  when: sap_system_hana_db_instance_nr is not defined


- name: Interactive input - Set facts from prompts
  ansible.builtin.set_fact:
    sap_hana_product_input: "{{ sap_hana_product_input_register.user_input
      if sap_hana_product_input_register.user_input is defined and sap_hana_product_input_register.user_input
      else sap_hana_product_input }}"
    sap_hana_install_use_master_password: "{{ sap_hana_install_use_master_password_register.user_input
      if sap_hana_install_use_master_password_register.user_input is defined and sap_hana_install_use_master_password_register.user_input
      else sap_hana_install_use_master_password | d('y')}}"
    sap_hana_install_master_password: "{{ sap_hana_install_master_password_register.user_input
      if sap_hana_install_master_password_register.user_input is defined and sap_hana_install_master_password_register.user_input
      else sap_hana_install_master_password }}"

    # Assignment of playbook wide variables
    sap_system_hana_db_sid: "{{ sap_system_hana_db_sid_register.user_input
      if sap_system_hana_db_sid_register.user_input is defined
      else sap_system_hana_db_sid }}"
    sap_system_hana_db_instance_nr: "{{ sap_system_hana_db_instance_nr_register.user_input
      if sap_system_hana_db_instance_nr_register.user_input is defined
      else sap_system_hana_db_instance_nr }}"


# Optional inputs
- name: Interactive input - Optional inputs
  ansible.builtin.pause:
    prompt: "Please enter yes if you would like to enter optional inputs. (yes/no). Default: no"
  register: __optional_inputs_hana
  no_log: true

- name: Block for optional interactive inputs
  when: __optional_inputs_hana.user_input== 'yes'
  block:
    - name: Interactive input - sap_hana_install_log_mode
      ansible.builtin.pause:
        prompt: "Please enter Log mode of SAP HANA from list: normal, overwrite. Default: normal"
      register: sap_hana_install_log_mode_register
      failed_when: sap_hana_install_log_mode_register.user_input not in ['normal', 'overwrite']
      when: sap_hana_install_log_mode is not defined or not sap_hana_install_log_mode

    - name: Interactive input - sap_hana_install_update_etchosts
      ansible.builtin.pause:
        prompt: "(Optional) Please select if /etc/hosts should be updated (true/false). Default: false"
      register: sap_hana_install_update_etchosts_register
      failed_when: sap_hana_install_update_etchosts_register.user_input not in ['true', 'false']
      when: sap_hana_install_update_etchosts is not defined

    - name: Interactive input - sap_hana_install_components
      ansible.builtin.pause:
        prompt: "(Optional) Please enter comma separated list of components to install. Default: all"
      register: sap_hana_install_components_register
      no_log: true
      when: sap_hana_install_components is not defined or not sap_hana_install_components

    - name: Interactive input - sap_hana_install_userid
      ansible.builtin.pause:
        prompt: "(Optional) Please enter user ID of unix user."
      register: sap_hana_install_userid_register
      no_log: true
      when: sap_hana_install_userid is not defined or not sap_hana_install_userid

    - name: Interactive input - sap_hana_install_groupid
      ansible.builtin.pause:
        prompt: "(Optional) Please enter group ID of unix user."
      register: sap_hana_install_groupid_register
      no_log: true
      when: sap_hana_install_groupid is not defined or not sap_hana_install_groupid

    - name: Interactive input - sap_hana_install_system_usage
      ansible.builtin.pause:
        prompt: "(Optional) Please enter hdblcm parameter system_usage. Default: custom"
      register: sap_hana_install_system_usage_register
      no_log: true
      when: sap_hana_install_system_usage is not defined or not sap_hana_install_system_usage

    - name: Interactive input - sap_hana_install_restrict_max_mem
      ansible.builtin.pause:
        prompt: "(Optional) Please enter hdblcm parameter restrict_max_mem (y/n). Default: n"
      register: sap_hana_install_restrict_max_mem_register
      failed_when: sap_hana_install_restrict_max_mem_register.user_input not in ['y', 'n']
      when: sap_hana_install_restrict_max_mem is not defined

    - name: Interactive input - sap_hana_install_max_mem
      ansible.builtin.pause:
        prompt: "(Optional) Please enter hdblcm parameter max_mem in MB. Required when restrict_max_mem is y"
      register: sap_hana_install_max_mem_register
      no_log: true
      when: sap_hana_install_max_mem is not defined

    - name: Interactive input - sap_hana_install_system_restart
      ansible.builtin.pause:
        prompt: "(Optional) Please select if role should start SAP HANA after each system boot (y/n). Default: n"
      register: sap_hana_install_system_restart_register
      failed_when: sap_hana_install_system_restart_register.user_input not in ['y', 'n']
      when: sap_hana_install_system_restart is not defined

    - name: Interactive input - sap_hana_install_hdblcm_extraargs
      ansible.builtin.pause:
        prompt: "(Optional) Please enter list of extra arguments to hdblcm cli, e.g.  --ignore=<check1>[,<check2>]..."
      register: sap_hana_install_hdblcm_extraargs_register
      no_log: true
      when: sap_hana_install_hdblcm_extraargs is not defined or not sap_hana_install_hdblcm_extraargs


    - name: Interactive input - Set facts from prompts
      ansible.builtin.set_fact:
        sap_hana_install_log_mode: "{{ sap_hana_install_log_mode_register.user_input }}"
        sap_hana_install_update_etchosts: "{{ sap_hana_install_update_etchosts_register.user_input | bool }}"
        sap_hana_install_components: "{{ sap_hana_install_components_register.user_input }}"
        sap_hana_install_userid: "{{ sap_hana_install_userid_register.user_input }}"
        sap_hana_install_groupid: "{{ sap_hana_install_groupid_register.user_input }}"
        sap_hana_install_system_usage: "{{ sap_hana_install_system_usage_register.user_input }}"
        sap_hana_install_restrict_max_mem: "{{ sap_hana_install_restrict_max_mem_register.user_input }}"
        sap_hana_install_max_mem: "{{ sap_hana_install_max_mem_register.user_input }}"
        sap_hana_install_system_restart: "{{ sap_hana_install_system_restart_register.user_input }}"
        sap_hana_install_hdblcm_extraargs: "{{ sap_hana_install_hdblcm_extraargs_register.user_input }}"
